// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.j1987.coffeeroo.domain;

import com.j1987.coffeeroo.domain.JDealer;
import com.j1987.coffeeroo.domain.JDealerDataOnDemand;
import com.j1987.coffeeroo.domain.JDealerIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect JDealerIntegrationTest_Roo_IntegrationTest {
    
    declare @type: JDealerIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: JDealerIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: JDealerIntegrationTest: @Transactional;
    
    @Autowired
    JDealerDataOnDemand JDealerIntegrationTest.dod;
    
    @Test
    public void JDealerIntegrationTest.testCountJDealers() {
        Assert.assertNotNull("Data on demand for 'JDealer' failed to initialize correctly", dod.getRandomJDealer());
        long count = JDealer.countJDealers();
        Assert.assertTrue("Counter for 'JDealer' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void JDealerIntegrationTest.testFindJDealer() {
        JDealer obj = dod.getRandomJDealer();
        Assert.assertNotNull("Data on demand for 'JDealer' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JDealer' failed to provide an identifier", id);
        obj = JDealer.findJDealer(id);
        Assert.assertNotNull("Find method for 'JDealer' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'JDealer' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void JDealerIntegrationTest.testFindAllJDealers() {
        Assert.assertNotNull("Data on demand for 'JDealer' failed to initialize correctly", dod.getRandomJDealer());
        long count = JDealer.countJDealers();
        Assert.assertTrue("Too expensive to perform a find all test for 'JDealer', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<JDealer> result = JDealer.findAllJDealers();
        Assert.assertNotNull("Find all method for 'JDealer' illegally returned null", result);
        Assert.assertTrue("Find all method for 'JDealer' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void JDealerIntegrationTest.testFindJDealerEntries() {
        Assert.assertNotNull("Data on demand for 'JDealer' failed to initialize correctly", dod.getRandomJDealer());
        long count = JDealer.countJDealers();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<JDealer> result = JDealer.findJDealerEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'JDealer' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'JDealer' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void JDealerIntegrationTest.testFlush() {
        JDealer obj = dod.getRandomJDealer();
        Assert.assertNotNull("Data on demand for 'JDealer' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JDealer' failed to provide an identifier", id);
        obj = JDealer.findJDealer(id);
        Assert.assertNotNull("Find method for 'JDealer' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyJDealer(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'JDealer' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void JDealerIntegrationTest.testMergeUpdate() {
        JDealer obj = dod.getRandomJDealer();
        Assert.assertNotNull("Data on demand for 'JDealer' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JDealer' failed to provide an identifier", id);
        obj = JDealer.findJDealer(id);
        boolean modified =  dod.modifyJDealer(obj);
        Integer currentVersion = obj.getVersion();
        JDealer merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'JDealer' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void JDealerIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'JDealer' failed to initialize correctly", dod.getRandomJDealer());
        JDealer obj = dod.getNewTransientJDealer(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'JDealer' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'JDealer' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'JDealer' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void JDealerIntegrationTest.testRemove() {
        JDealer obj = dod.getRandomJDealer();
        Assert.assertNotNull("Data on demand for 'JDealer' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JDealer' failed to provide an identifier", id);
        obj = JDealer.findJDealer(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'JDealer' with identifier '" + id + "'", JDealer.findJDealer(id));
    }
    
}
