// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.j1987.coffeeroo.domain;

import com.j1987.coffeeroo.domain.JDealer;
import com.j1987.coffeeroo.domain.JDealerDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect JDealerDataOnDemand_Roo_DataOnDemand {
    
    declare @type: JDealerDataOnDemand: @Component;
    
    private Random JDealerDataOnDemand.rnd = new SecureRandom();
    
    private List<JDealer> JDealerDataOnDemand.data;
    
    public JDealer JDealerDataOnDemand.getNewTransientJDealer(int index) {
        JDealer obj = new JDealer();
        setCode(obj, index);
        setDescription(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void JDealerDataOnDemand.setCode(JDealer obj, int index) {
        String code = "code_" + index;
        obj.setCode(code);
    }
    
    public void JDealerDataOnDemand.setDescription(JDealer obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void JDealerDataOnDemand.setName(JDealer obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public JDealer JDealerDataOnDemand.getSpecificJDealer(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        JDealer obj = data.get(index);
        Long id = obj.getId();
        return JDealer.findJDealer(id);
    }
    
    public JDealer JDealerDataOnDemand.getRandomJDealer() {
        init();
        JDealer obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return JDealer.findJDealer(id);
    }
    
    public boolean JDealerDataOnDemand.modifyJDealer(JDealer obj) {
        return false;
    }
    
    public void JDealerDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = JDealer.findJDealerEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'JDealer' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<JDealer>();
        for (int i = 0; i < 10; i++) {
            JDealer obj = getNewTransientJDealer(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
