// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.j1987.coffeeroo.domain;

import com.j1987.coffeeroo.domain.JFactory;
import com.j1987.coffeeroo.domain.JFactoryDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect JFactoryDataOnDemand_Roo_DataOnDemand {
    
    declare @type: JFactoryDataOnDemand: @Component;
    
    private Random JFactoryDataOnDemand.rnd = new SecureRandom();
    
    private List<JFactory> JFactoryDataOnDemand.data;
    
    public JFactory JFactoryDataOnDemand.getNewTransientJFactory(int index) {
        JFactory obj = new JFactory();
        setCode(obj, index);
        setDescription(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void JFactoryDataOnDemand.setCode(JFactory obj, int index) {
        String code = "code_" + index;
        obj.setCode(code);
    }
    
    public void JFactoryDataOnDemand.setDescription(JFactory obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void JFactoryDataOnDemand.setName(JFactory obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public JFactory JFactoryDataOnDemand.getSpecificJFactory(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        JFactory obj = data.get(index);
        Long id = obj.getId();
        return JFactory.findJFactory(id);
    }
    
    public JFactory JFactoryDataOnDemand.getRandomJFactory() {
        init();
        JFactory obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return JFactory.findJFactory(id);
    }
    
    public boolean JFactoryDataOnDemand.modifyJFactory(JFactory obj) {
        return false;
    }
    
    public void JFactoryDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = JFactory.findJFactoryEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'JFactory' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<JFactory>();
        for (int i = 0; i < 10; i++) {
            JFactory obj = getNewTransientJFactory(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
