// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.j1987.coffeeroo.domain;

import com.j1987.coffeeroo.domain.JRole;
import com.j1987.coffeeroo.domain.JRoleDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect JRoleDataOnDemand_Roo_DataOnDemand {
    
    declare @type: JRoleDataOnDemand: @Component;
    
    private Random JRoleDataOnDemand.rnd = new SecureRandom();
    
    private List<JRole> JRoleDataOnDemand.data;
    
    public JRole JRoleDataOnDemand.getNewTransientJRole(int index) {
        JRole obj = new JRole();
        setDescription(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void JRoleDataOnDemand.setDescription(JRole obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void JRoleDataOnDemand.setName(JRole obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public JRole JRoleDataOnDemand.getSpecificJRole(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        JRole obj = data.get(index);
        Long id = obj.getId();
        return JRole.findJRole(id);
    }
    
    public JRole JRoleDataOnDemand.getRandomJRole() {
        init();
        JRole obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return JRole.findJRole(id);
    }
    
    public boolean JRoleDataOnDemand.modifyJRole(JRole obj) {
        return false;
    }
    
    public void JRoleDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = JRole.findJRoleEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'JRole' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<JRole>();
        for (int i = 0; i < 10; i++) {
            JRole obj = getNewTransientJRole(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
