// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.j1987.coffeeroo.domain;

import com.j1987.coffeeroo.domain.JSubmissionForApproval;
import com.j1987.coffeeroo.domain.JSubmissionForApprovalDataOnDemand;
import com.j1987.coffeeroo.domain.JSubmissionForApprovalIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect JSubmissionForApprovalIntegrationTest_Roo_IntegrationTest {
    
    declare @type: JSubmissionForApprovalIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: JSubmissionForApprovalIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: JSubmissionForApprovalIntegrationTest: @Transactional;
    
    @Autowired
    JSubmissionForApprovalDataOnDemand JSubmissionForApprovalIntegrationTest.dod;
    
    @Test
    public void JSubmissionForApprovalIntegrationTest.testCountJSubmissionForApprovals() {
        Assert.assertNotNull("Data on demand for 'JSubmissionForApproval' failed to initialize correctly", dod.getRandomJSubmissionForApproval());
        long count = JSubmissionForApproval.countJSubmissionForApprovals();
        Assert.assertTrue("Counter for 'JSubmissionForApproval' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void JSubmissionForApprovalIntegrationTest.testFindJSubmissionForApproval() {
        JSubmissionForApproval obj = dod.getRandomJSubmissionForApproval();
        Assert.assertNotNull("Data on demand for 'JSubmissionForApproval' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JSubmissionForApproval' failed to provide an identifier", id);
        obj = JSubmissionForApproval.findJSubmissionForApproval(id);
        Assert.assertNotNull("Find method for 'JSubmissionForApproval' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'JSubmissionForApproval' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void JSubmissionForApprovalIntegrationTest.testFindAllJSubmissionForApprovals() {
        Assert.assertNotNull("Data on demand for 'JSubmissionForApproval' failed to initialize correctly", dod.getRandomJSubmissionForApproval());
        long count = JSubmissionForApproval.countJSubmissionForApprovals();
        Assert.assertTrue("Too expensive to perform a find all test for 'JSubmissionForApproval', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<JSubmissionForApproval> result = JSubmissionForApproval.findAllJSubmissionForApprovals();
        Assert.assertNotNull("Find all method for 'JSubmissionForApproval' illegally returned null", result);
        Assert.assertTrue("Find all method for 'JSubmissionForApproval' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void JSubmissionForApprovalIntegrationTest.testFindJSubmissionForApprovalEntries() {
        Assert.assertNotNull("Data on demand for 'JSubmissionForApproval' failed to initialize correctly", dod.getRandomJSubmissionForApproval());
        long count = JSubmissionForApproval.countJSubmissionForApprovals();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<JSubmissionForApproval> result = JSubmissionForApproval.findJSubmissionForApprovalEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'JSubmissionForApproval' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'JSubmissionForApproval' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void JSubmissionForApprovalIntegrationTest.testFlush() {
        JSubmissionForApproval obj = dod.getRandomJSubmissionForApproval();
        Assert.assertNotNull("Data on demand for 'JSubmissionForApproval' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JSubmissionForApproval' failed to provide an identifier", id);
        obj = JSubmissionForApproval.findJSubmissionForApproval(id);
        Assert.assertNotNull("Find method for 'JSubmissionForApproval' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyJSubmissionForApproval(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'JSubmissionForApproval' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void JSubmissionForApprovalIntegrationTest.testMergeUpdate() {
        JSubmissionForApproval obj = dod.getRandomJSubmissionForApproval();
        Assert.assertNotNull("Data on demand for 'JSubmissionForApproval' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JSubmissionForApproval' failed to provide an identifier", id);
        obj = JSubmissionForApproval.findJSubmissionForApproval(id);
        boolean modified =  dod.modifyJSubmissionForApproval(obj);
        Integer currentVersion = obj.getVersion();
        JSubmissionForApproval merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'JSubmissionForApproval' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void JSubmissionForApprovalIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'JSubmissionForApproval' failed to initialize correctly", dod.getRandomJSubmissionForApproval());
        JSubmissionForApproval obj = dod.getNewTransientJSubmissionForApproval(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'JSubmissionForApproval' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'JSubmissionForApproval' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'JSubmissionForApproval' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void JSubmissionForApprovalIntegrationTest.testRemove() {
        JSubmissionForApproval obj = dod.getRandomJSubmissionForApproval();
        Assert.assertNotNull("Data on demand for 'JSubmissionForApproval' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JSubmissionForApproval' failed to provide an identifier", id);
        obj = JSubmissionForApproval.findJSubmissionForApproval(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'JSubmissionForApproval' with identifier '" + id + "'", JSubmissionForApproval.findJSubmissionForApproval(id));
    }
    
}
