// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.j1987.coffeeroo.domain;

import com.j1987.coffeeroo.domain.JSupplier;
import com.j1987.coffeeroo.domain.JSupplierDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect JSupplierDataOnDemand_Roo_DataOnDemand {
    
    declare @type: JSupplierDataOnDemand: @Component;
    
    private Random JSupplierDataOnDemand.rnd = new SecureRandom();
    
    private List<JSupplier> JSupplierDataOnDemand.data;
    
    public JSupplier JSupplierDataOnDemand.getNewTransientJSupplier(int index) {
        JSupplier obj = new JSupplier();
        setCode(obj, index);
        setDescription(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void JSupplierDataOnDemand.setCode(JSupplier obj, int index) {
        String code = "code_" + index;
        obj.setCode(code);
    }
    
    public void JSupplierDataOnDemand.setDescription(JSupplier obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void JSupplierDataOnDemand.setName(JSupplier obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public JSupplier JSupplierDataOnDemand.getSpecificJSupplier(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        JSupplier obj = data.get(index);
        Long id = obj.getId();
        return JSupplier.findJSupplier(id);
    }
    
    public JSupplier JSupplierDataOnDemand.getRandomJSupplier() {
        init();
        JSupplier obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return JSupplier.findJSupplier(id);
    }
    
    public boolean JSupplierDataOnDemand.modifyJSupplier(JSupplier obj) {
        return false;
    }
    
    public void JSupplierDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = JSupplier.findJSupplierEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'JSupplier' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<JSupplier>();
        for (int i = 0; i < 10; i++) {
            JSupplier obj = getNewTransientJSupplier(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
