// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.j1987.coffeeroo.domain;

import com.j1987.coffeeroo.domain.JSupplier;
import com.j1987.coffeeroo.domain.JSupplierDataOnDemand;
import com.j1987.coffeeroo.domain.JSupplierIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect JSupplierIntegrationTest_Roo_IntegrationTest {
    
    declare @type: JSupplierIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: JSupplierIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: JSupplierIntegrationTest: @Transactional;
    
    @Autowired
    JSupplierDataOnDemand JSupplierIntegrationTest.dod;
    
    @Test
    public void JSupplierIntegrationTest.testCountJSuppliers() {
        Assert.assertNotNull("Data on demand for 'JSupplier' failed to initialize correctly", dod.getRandomJSupplier());
        long count = JSupplier.countJSuppliers();
        Assert.assertTrue("Counter for 'JSupplier' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void JSupplierIntegrationTest.testFindJSupplier() {
        JSupplier obj = dod.getRandomJSupplier();
        Assert.assertNotNull("Data on demand for 'JSupplier' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JSupplier' failed to provide an identifier", id);
        obj = JSupplier.findJSupplier(id);
        Assert.assertNotNull("Find method for 'JSupplier' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'JSupplier' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void JSupplierIntegrationTest.testFindAllJSuppliers() {
        Assert.assertNotNull("Data on demand for 'JSupplier' failed to initialize correctly", dod.getRandomJSupplier());
        long count = JSupplier.countJSuppliers();
        Assert.assertTrue("Too expensive to perform a find all test for 'JSupplier', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<JSupplier> result = JSupplier.findAllJSuppliers();
        Assert.assertNotNull("Find all method for 'JSupplier' illegally returned null", result);
        Assert.assertTrue("Find all method for 'JSupplier' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void JSupplierIntegrationTest.testFindJSupplierEntries() {
        Assert.assertNotNull("Data on demand for 'JSupplier' failed to initialize correctly", dod.getRandomJSupplier());
        long count = JSupplier.countJSuppliers();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<JSupplier> result = JSupplier.findJSupplierEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'JSupplier' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'JSupplier' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void JSupplierIntegrationTest.testFlush() {
        JSupplier obj = dod.getRandomJSupplier();
        Assert.assertNotNull("Data on demand for 'JSupplier' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JSupplier' failed to provide an identifier", id);
        obj = JSupplier.findJSupplier(id);
        Assert.assertNotNull("Find method for 'JSupplier' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyJSupplier(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'JSupplier' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void JSupplierIntegrationTest.testMergeUpdate() {
        JSupplier obj = dod.getRandomJSupplier();
        Assert.assertNotNull("Data on demand for 'JSupplier' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JSupplier' failed to provide an identifier", id);
        obj = JSupplier.findJSupplier(id);
        boolean modified =  dod.modifyJSupplier(obj);
        Integer currentVersion = obj.getVersion();
        JSupplier merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'JSupplier' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void JSupplierIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'JSupplier' failed to initialize correctly", dod.getRandomJSupplier());
        JSupplier obj = dod.getNewTransientJSupplier(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'JSupplier' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'JSupplier' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'JSupplier' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void JSupplierIntegrationTest.testRemove() {
        JSupplier obj = dod.getRandomJSupplier();
        Assert.assertNotNull("Data on demand for 'JSupplier' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JSupplier' failed to provide an identifier", id);
        obj = JSupplier.findJSupplier(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'JSupplier' with identifier '" + id + "'", JSupplier.findJSupplier(id));
    }
    
}
