// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.j1987.coffeeroo.domain;

import com.j1987.coffeeroo.domain.JTour;
import com.j1987.coffeeroo.domain.JTourDataOnDemand;
import com.j1987.coffeeroo.domain.JTourIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect JTourIntegrationTest_Roo_IntegrationTest {
    
    declare @type: JTourIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: JTourIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: JTourIntegrationTest: @Transactional;
    
    @Autowired
    JTourDataOnDemand JTourIntegrationTest.dod;
    
    @Test
    public void JTourIntegrationTest.testCountJTours() {
        Assert.assertNotNull("Data on demand for 'JTour' failed to initialize correctly", dod.getRandomJTour());
        long count = JTour.countJTours();
        Assert.assertTrue("Counter for 'JTour' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void JTourIntegrationTest.testFindJTour() {
        JTour obj = dod.getRandomJTour();
        Assert.assertNotNull("Data on demand for 'JTour' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JTour' failed to provide an identifier", id);
        obj = JTour.findJTour(id);
        Assert.assertNotNull("Find method for 'JTour' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'JTour' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void JTourIntegrationTest.testFindAllJTours() {
        Assert.assertNotNull("Data on demand for 'JTour' failed to initialize correctly", dod.getRandomJTour());
        long count = JTour.countJTours();
        Assert.assertTrue("Too expensive to perform a find all test for 'JTour', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<JTour> result = JTour.findAllJTours();
        Assert.assertNotNull("Find all method for 'JTour' illegally returned null", result);
        Assert.assertTrue("Find all method for 'JTour' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void JTourIntegrationTest.testFindJTourEntries() {
        Assert.assertNotNull("Data on demand for 'JTour' failed to initialize correctly", dod.getRandomJTour());
        long count = JTour.countJTours();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<JTour> result = JTour.findJTourEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'JTour' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'JTour' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void JTourIntegrationTest.testFlush() {
        JTour obj = dod.getRandomJTour();
        Assert.assertNotNull("Data on demand for 'JTour' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JTour' failed to provide an identifier", id);
        obj = JTour.findJTour(id);
        Assert.assertNotNull("Find method for 'JTour' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyJTour(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'JTour' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void JTourIntegrationTest.testMergeUpdate() {
        JTour obj = dod.getRandomJTour();
        Assert.assertNotNull("Data on demand for 'JTour' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JTour' failed to provide an identifier", id);
        obj = JTour.findJTour(id);
        boolean modified =  dod.modifyJTour(obj);
        Integer currentVersion = obj.getVersion();
        JTour merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'JTour' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void JTourIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'JTour' failed to initialize correctly", dod.getRandomJTour());
        JTour obj = dod.getNewTransientJTour(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'JTour' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'JTour' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'JTour' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void JTourIntegrationTest.testRemove() {
        JTour obj = dod.getRandomJTour();
        Assert.assertNotNull("Data on demand for 'JTour' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JTour' failed to provide an identifier", id);
        obj = JTour.findJTour(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'JTour' with identifier '" + id + "'", JTour.findJTour(id));
    }
    
}
