// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.j1987.coffeeroo.domain;

import com.j1987.coffeeroo.domain.JUser;
import com.j1987.coffeeroo.domain.JUserDataOnDemand;
import com.j1987.coffeeroo.domain.JUserIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect JUserIntegrationTest_Roo_IntegrationTest {
    
    declare @type: JUserIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: JUserIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: JUserIntegrationTest: @Transactional;
    
    @Autowired
    JUserDataOnDemand JUserIntegrationTest.dod;
    
    @Test
    public void JUserIntegrationTest.testCountJUsers() {
        Assert.assertNotNull("Data on demand for 'JUser' failed to initialize correctly", dod.getRandomJUser());
        long count = JUser.countJUsers();
        Assert.assertTrue("Counter for 'JUser' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void JUserIntegrationTest.testFindJUser() {
        JUser obj = dod.getRandomJUser();
        Assert.assertNotNull("Data on demand for 'JUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JUser' failed to provide an identifier", id);
        obj = JUser.findJUser(id);
        Assert.assertNotNull("Find method for 'JUser' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'JUser' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void JUserIntegrationTest.testFindAllJUsers() {
        Assert.assertNotNull("Data on demand for 'JUser' failed to initialize correctly", dod.getRandomJUser());
        long count = JUser.countJUsers();
        Assert.assertTrue("Too expensive to perform a find all test for 'JUser', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<JUser> result = JUser.findAllJUsers();
        Assert.assertNotNull("Find all method for 'JUser' illegally returned null", result);
        Assert.assertTrue("Find all method for 'JUser' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void JUserIntegrationTest.testFindJUserEntries() {
        Assert.assertNotNull("Data on demand for 'JUser' failed to initialize correctly", dod.getRandomJUser());
        long count = JUser.countJUsers();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<JUser> result = JUser.findJUserEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'JUser' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'JUser' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void JUserIntegrationTest.testFlush() {
        JUser obj = dod.getRandomJUser();
        Assert.assertNotNull("Data on demand for 'JUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JUser' failed to provide an identifier", id);
        obj = JUser.findJUser(id);
        Assert.assertNotNull("Find method for 'JUser' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyJUser(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'JUser' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void JUserIntegrationTest.testMergeUpdate() {
        JUser obj = dod.getRandomJUser();
        Assert.assertNotNull("Data on demand for 'JUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JUser' failed to provide an identifier", id);
        obj = JUser.findJUser(id);
        boolean modified =  dod.modifyJUser(obj);
        Integer currentVersion = obj.getVersion();
        JUser merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'JUser' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void JUserIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'JUser' failed to initialize correctly", dod.getRandomJUser());
        JUser obj = dod.getNewTransientJUser(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'JUser' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'JUser' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'JUser' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void JUserIntegrationTest.testRemove() {
        JUser obj = dod.getRandomJUser();
        Assert.assertNotNull("Data on demand for 'JUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JUser' failed to provide an identifier", id);
        obj = JUser.findJUser(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'JUser' with identifier '" + id + "'", JUser.findJUser(id));
    }
    
}
