// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.j1987.coffeeroo.domain;

import com.j1987.coffeeroo.domain.JSupplier;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect JSupplier_Roo_Configurable {
    
    declare @type: JSupplier: @Configurable;
    
}
